### ISSUE TITLE
Run PyMC3 test suite

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/Theano-PyMC#163]
With all this heavy development work it will be very easy to inadvertently break PyMC3 which we will only discover in unrelated PyMC3 PRs. I thus propose to run the PyMC3 tests for Theano PRs as well.

**Comment by brandonwillard** [comment]
We should continue to keep PyMC3 and Theano-PyMC separate.  If we want to avoid conflicts between the two, we can simply pin the Theano-PyMC version in PyMC3.

Otherwise, adding the PyMC3 tests to this project would greatly increase the test time and provide questionable coverage/quality improvements given the cost.  Such an addition would have us going down the same path that led to Theano-PyMC's current test suite, and only result in more brittle, long-running, indirect "shotgun"-approach tests.

Instead, as we find problems, we need to write good unit tests that do not unnecessarily rely on other, unrelated pieces of code (e.g. create distinct objects for testing that meet a test condition instead of relying on existing objects that are prone to change).  They also need to explicitly target the code they're testing (e.g. purposefully set the compilation modes and optimizations used in a test).  Those basics&mdash;plus a higher standard of coverage&mdash;will dramatically improve this project in no time.

**Comment by twiecki** [comment]
I think you're right about pegging the version.

**Comment by brandonwillard** [comment]
FYI: I pinned the version in pymc-devs/pymc3#4218.
