### ISSUE TITLE
Publish Conda and PyPi builds through GitHub Actions

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#77]
We need GitHub Actions workflows for publishing Conda and PyPi builds.

**Comment by dfm** [comment]
PyPI is easy and I'm happy to add that! I don't have as much experience with the conda, but I'm happy to take a shot.

**Comment by brandonwillard** [comment]
That would be great!  We can't really get it running until secrets containing the PyPi and conda-forge tokens are added (@twiecki), but&mdash;in the meantime&mdash;it can't hurt to have a PR with those workflows ready.

**Comment by dfm** [comment]
Re: conda: Is the idea to upload to the defaults channel or do we only care about conda-forge? If the latter, then #78 is enough because the conda-forge builds are done on https://github.com/conda-forge/theano-feedstock. If we have access to and want to update the build on `defaults` (it looks like that hasn't been done so far) then that is above my pay grade :D

**Comment by brandonwillard** [comment]
I think [`theano-pymc-feedstock`](https://github.com/conda-forge/theano-pymc-feedstock) is the one for this repo, but, yeah, I guess we shouldn't need to do anything special for `conda-forge`, and I don't think we need it on the defaults channel either.  @twiecki, does that sound correct?

**Comment by twiecki** [comment]
Yeah, default channel is not worth the effort, and with new releases we cut
here and upload to pypi the feedstock will update and release automatically.

**Comment by brandonwillard** [comment]
I just created a release, and [it works](https://pypi.org/project/Theano-PyMC/)!  

Note: apparently, you can't trigger the release action from `git` remotely; you must use the GitHub site to create a release.
